PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX swco: <http://www.seiri.studio/swco/>

# SPARQL query begins
SELECT ?card ?order
WHERE {
    ?list  swco:id "${listId}" .
    ?list swco:hasCard ?card .
    ?card swco:order ?order .
} 
ORDER BY DESC(?order)
LIMIT 1