"use strict";
// // Import the data_categories array from '@/app/data'
// import { data_categories } from '@/app/data';
Object.defineProperty(exports, "__esModule", { value: true });
exports.data_categories = void 0;
exports.data_categories = [
    {
        "fides_key": "data_category",
        "is_default": "True",
        "name": "Data Category",
        "organization_fides_key": "default_organization",
        "parent_key": "",
        "replaced_by": "",
        "tags": "2.0.0",
        "version_added": "",
        "version_deprecated": "Data unique to",
        "description": "and under control of the system."
    },
    {
        "fides_key": "user.personality_rights",
        "is_default": "True",
        "name": "Personality Rights Data",
        "organization_fides_key": "default_organization",
        "parent_key": "data_category",
        "replaced_by": "",
        "tags": "2.0.0",
        "version_added": "",
        "version_deprecated": "Data reflecting aspects of a user's identity protected by personality rights.",
        "description": ""
    },
    {
        "fides_key": "system",
        "is_default": "True",
        "name": "System Data",
        "organization_fides_key": "default_organization",
        "parent_key": "data_category",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data unique to, and under control of the system."
    },
    {
        "fides_key": "system.authentication",
        "is_default": "True",
        "name": "Authentication Data",
        "organization_fides_key": "default_organization",
        "parent_key": "system",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data used to manage access to the system."
    },
    {
        "fides_key": "system.operations",
        "is_default": "True",
        "name": "Operations Data",
        "organization_fides_key": "default_organization",
        "parent_key": "system",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data used for system operations."
    },
    {
        "fides_key": "user",
        "is_default": "True",
        "name": "User Data",
        "organization_fides_key": "default_organization",
        "parent_key": "data_category",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data related to the user of the system, either provided directly or derived based on their usage."
    },
    {
        "fides_key": "user.account",
        "is_default": "True",
        "name": "Account Information",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Account creation or registration information."
    },
    {
        "fides_key": "user.authorization",
        "is_default": "True",
        "name": "Authorization Information",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Scope of permissions and access to a system."
    },
    {
        "fides_key": "user.behavior",
        "is_default": "True",
        "name": "Observed Behavior",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Behavioral data about the subject."
    },
    {
        "fides_key": "user.biometric",
        "is_default": "True",
        "name": "Biometric Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Encoded characteristics provided by a user."
    },
    {
        "fides_key": "user.childrens",
        "is_default": "True",
        "name": "Children's Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data relating to children."
    },
    {
        "fides_key": "user.contact",
        "is_default": "True",
        "name": "Contact Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Contact data collected about a user."
    },
    {
        "fides_key": "user.content",
        "is_default": "True",
        "name": "User Content",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Content related to, or created by the subject."
    },
    {
        "fides_key": "user.demographic",
        "is_default": "True",
        "name": "Demographic Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Demographic data about a user."
    },
    {
        "fides_key": "user.location",
        "is_default": "True",
        "name": "Location Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Records of the location of a user."
    },
    {
        "fides_key": "user.device",
        "is_default": "True",
        "name": "Device Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data related to a user's device, configuration and setting."
    },
    {
        "fides_key": "user.payment",
        "is_default": "True",
        "name": "Payment Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Payment data related to user."
    },
    {
        "fides_key": "user.social",
        "is_default": "True",
        "name": "Social Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Social activity and interaction data."
    },
    {
        "fides_key": "user.unique_id",
        "is_default": "True",
        "name": "Unique ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Unique identifier for a user assigned through system use."
    },
    {
        "fides_key": "user.telemetry",
        "is_default": "True",
        "name": "Telemetry Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User identifiable measurement data from system sensors and monitoring."
    },
    {
        "fides_key": "user.user_sensor",
        "is_default": "True",
        "name": "User Sensor Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Measurement data about a user's environment through system use."
    },
    {
        "fides_key": "user.workplace",
        "is_default": "True",
        "name": "Workplace",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Organization of employment."
    },
    {
        "fides_key": "user.sensor",
        "is_default": "True",
        "name": "Sensor Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Measurement data from sensors and monitoring systems."
    },
    {
        "fides_key": "user.financial",
        "is_default": "True",
        "name": "Financial Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Payment data and financial history."
    },
    {
        "fides_key": "user.government_id",
        "is_default": "True",
        "name": "Government ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State provided identification data."
    },
    {
        "fides_key": "user.health_and_medical",
        "is_default": "True",
        "name": "Health and Medical Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Health records or individual's personal medical information."
    },
    {
        "fides_key": "user.name",
        "is_default": "True",
        "name": "Name",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's real name."
    },
    {
        "fides_key": "user.criminal_history",
        "is_default": "True",
        "name": "Criminal History",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Criminal records or information about the data subject."
    },
    {
        "fides_key": "user.privacy_preferences",
        "is_default": "True",
        "name": "Privacy Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Privacy preferences or settings set by the subject."
    },
    {
        "fides_key": "user.job_title",
        "is_default": "True",
        "name": "Job Title",
        "organization_fides_key": "default_organization",
        "parent_key": "user",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Professional data."
    },
    {
        "fides_key": "user.account.settings",
        "is_default": "True",
        "name": "Account Settings",
        "organization_fides_key": "default_organization",
        "parent_key": "user.account",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Account preferences and settings."
    },
    {
        "fides_key": "user.account.username",
        "is_default": "True",
        "name": "Account Username",
        "organization_fides_key": "default_organization",
        "parent_key": "user.account",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Username associated with account."
    },
    {
        "fides_key": "user.authorization.credentials",
        "is_default": "True",
        "name": "Account password",
        "organization_fides_key": "default_organization",
        "parent_key": "user.authorization",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Authentication credentials to a system."
    },
    {
        "fides_key": "user.authorization.biometric",
        "is_default": "True",
        "name": "Biometric Credentials",
        "organization_fides_key": "default_organization",
        "parent_key": "user.authorization",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Credentials for system authentication."
    },
    {
        "fides_key": "user.authorization.password",
        "is_default": "True",
        "name": "Password",
        "organization_fides_key": "default_organization",
        "parent_key": "user.authorization",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Password for system authentication."
    },
    {
        "fides_key": "user.behavior.browsing_history",
        "is_default": "True",
        "name": "Browsing History",
        "organization_fides_key": "default_organization",
        "parent_key": "user.behavior",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Content browsing history of a user."
    },
    {
        "fides_key": "user.behavior.media_consumption",
        "is_default": "True",
        "name": "Media Consumption",
        "organization_fides_key": "default_organization",
        "parent_key": "user.behavior",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Content consumption history of the subject."
    },
    {
        "fides_key": "user.behavior.purchase_history",
        "is_default": "True",
        "name": "Purchase History",
        "organization_fides_key": "default_organization",
        "parent_key": "user.behavior",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Purchase history of the subject."
    },
    {
        "fides_key": "user.behavior.search_history",
        "is_default": "True",
        "name": "Search History",
        "organization_fides_key": "default_organization",
        "parent_key": "user.behavior",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Search history of the subject."
    },
    {
        "fides_key": "user.biometric.fingerprint",
        "is_default": "True",
        "name": "Fingerprint",
        "organization_fides_key": "default_organization",
        "parent_key": "user.biometric",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Fingerprint encoded data about a subject."
    },
    {
        "fides_key": "user.biometric.retinal",
        "is_default": "True",
        "name": "Retina Scan",
        "organization_fides_key": "default_organization",
        "parent_key": "user.biometric",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Retinal data about a subject."
    },
    {
        "fides_key": "user.biometric.voice",
        "is_default": "True",
        "name": "Voice Recording",
        "organization_fides_key": "default_organization",
        "parent_key": "user.biometric",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Voice encoded data about a subject."
    },
    {
        "fides_key": "user.biometric.health",
        "is_default": "True",
        "name": "Biometric Health Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user.biometric",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Encoded characteristic collected about a user."
    },
    {
        "fides_key": "user.contact.address",
        "is_default": "True",
        "name": "User Contact Address",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Contact address data collected about a user."
    },
    {
        "fides_key": "user.contact.email",
        "is_default": "True",
        "name": "User Contact Email",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's contact email address."
    },
    {
        "fides_key": "user.contact.phone_number",
        "is_default": "True",
        "name": "User Contact Phone Number",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's phone number."
    },
    {
        "fides_key": "user.contact.url",
        "is_default": "True",
        "name": "User Website",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Subject's websites or links to social and personal profiles."
    },
    {
        "fides_key": "user.contact.fax_number",
        "is_default": "True",
        "name": "Fax Number",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data Subject's fax number."
    },
    {
        "fides_key": "user.contact.organization",
        "is_default": "True",
        "name": "Organization",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data Subject's Organization."
    },
    {
        "fides_key": "user.contact.address.city",
        "is_default": "True",
        "name": "User Contact City",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact.address",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's city level address data."
    },
    {
        "fides_key": "user.contact.address.country",
        "is_default": "True",
        "name": "User Contact Country",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact.address",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's country level address data."
    },
    {
        "fides_key": "user.contact.address.postal_code",
        "is_default": "True",
        "name": "User Contact Postal Code",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact.address",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's postal code."
    },
    {
        "fides_key": "user.contact.address.state",
        "is_default": "True",
        "name": "User Contact State",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact.address",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's state level address data."
    },
    {
        "fides_key": "user.contact.address.street",
        "is_default": "True",
        "name": "User Contact Street",
        "organization_fides_key": "default_organization",
        "parent_key": "user.contact.address",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "User's street level address data."
    },
    {
        "fides_key": "user.content.private",
        "is_default": "True",
        "name": "Private Content",
        "organization_fides_key": "default_organization",
        "parent_key": "user.content",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Private content related to, or created by the subject, not publicly available."
    },
    {
        "fides_key": "user.content.public",
        "is_default": "True",
        "name": "Public Content",
        "organization_fides_key": "default_organization",
        "parent_key": "user.content",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Publicly shared Content related to, or created by the subject."
    },
    {
        "fides_key": "user.content.self_image",
        "is_default": "True",
        "name": "User Image",
        "organization_fides_key": "default_organization",
        "parent_key": "user.content",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Photograph or image in which subject is whole or partially recognized."
    },
    {
        "fides_key": "user.demographic.age_range",
        "is_default": "True",
        "name": "Age Range",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Non specific age or age-range of data subject."
    },
    {
        "fides_key": "user.demographic.date_of_birth",
        "is_default": "True",
        "name": "Birth Date",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Date of birth of data subject."
    },
    {
        "fides_key": "user.demographic.gender",
        "is_default": "True",
        "name": "Gender",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Gender of data subject."
    },
    {
        "fides_key": "user.demographic.language",
        "is_default": "True",
        "name": "Language",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Spoken or written language of subject."
    },
    {
        "fides_key": "user.demographic.marital_status",
        "is_default": "True",
        "name": "Marital Status",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Marital status of data subject."
    },
    {
        "fides_key": "user.demographic.political_opinion",
        "is_default": "True",
        "name": "Political Opinion",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Political opinion or belief of data subject."
    },
    {
        "fides_key": "user.demographic.profile",
        "is_default": "True",
        "name": "User Profile Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Profile or preference information about the data subject."
    },
    {
        "fides_key": "user.demographic.race_ethnicity",
        "is_default": "True",
        "name": "Race",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Race or ethnicity of data subject."
    },
    {
        "fides_key": "user.demographic.religious_belief",
        "is_default": "True",
        "name": "Religion",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Religion or religious beliefs of the data subject."
    },
    {
        "fides_key": "user.demographic.sexual_orientation",
        "is_default": "True",
        "name": "Sexual Orientation",
        "organization_fides_key": "default_organization",
        "parent_key": "user.demographic",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Sexual orientation of data subject."
    },
    {
        "fides_key": "user.device.cookie",
        "is_default": "True",
        "name": "Device Cookie",
        "organization_fides_key": "default_organization",
        "parent_key": "user.device",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data related to a subject, stored within a cookie."
    },
    {
        "fides_key": "user.device.cookie_id",
        "is_default": "True",
        "name": "Cookie ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.device",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Cookie unique identification number."
    },
    {
        "fides_key": "user.device.device_id",
        "is_default": "True",
        "name": "Device ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.device",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Device unique identification number."
    },
    {
        "fides_key": "user.device.ip_address",
        "is_default": "True",
        "name": "IP Address",
        "organization_fides_key": "default_organization",
        "parent_key": "user.device",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Unique identifier related to device connection."
    },
    {
        "fides_key": "user.financial.bank_account",
        "is_default": "True",
        "name": "Bank Account Information",
        "organization_fides_key": "default_organization",
        "parent_key": "user.financial",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Bank account information belonging to the subject."
    },
    {
        "fides_key": "user.financial.credit_card",
        "is_default": "True",
        "name": "Credit Card Information",
        "organization_fides_key": "default_organization",
        "parent_key": "user.financial",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Credit card information belonging to the subject."
    },
    {
        "fides_key": "user.government_id.birth_certificate",
        "is_default": "True",
        "name": "Birth Certificate",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued certificate of birth."
    },
    {
        "fides_key": "user.government_id.drivers_license_number",
        "is_default": "True",
        "name": "Driver's License Number",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued driving identification number."
    },
    {
        "fides_key": "user.government_id.immigration",
        "is_default": "True",
        "name": "Immigration ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued immigration or residency data."
    },
    {
        "fides_key": "user.government_id.national_identification_number",
        "is_default": "True",
        "name": "National Identification Number",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued personal identification number."
    },
    {
        "fides_key": "user.government_id.passport_number",
        "is_default": "True",
        "name": "Passport Number",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued passport data."
    },
    {
        "fides_key": "user.government_id.vehicle_registration",
        "is_default": "True",
        "name": "Vehicle Registration",
        "organization_fides_key": "default_organization",
        "parent_key": "user.government_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "State issued license plate or vehicle registration data."
    },
    {
        "fides_key": "user.health_and_medical.genetic",
        "is_default": "True",
        "name": "User's Genetic Data",
        "organization_fides_key": "default_organization",
        "parent_key": "user.health_and_medical",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Data about the genetic makeup provided by the subject."
    },
    {
        "fides_key": "user.health_and_medical.insurance_beneficiary_id",
        "is_default": "True",
        "name": "Medical Insurance ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.health_and_medical",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Health insurance beneficiary number of the subject."
    },
    {
        "fides_key": "user.health_and_medical.record_id",
        "is_default": "True",
        "name": "Medical Record ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.health_and_medical",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Medical record identifiers belonging to a subject."
    },
    {
        "fides_key": "user.location.imprecise",
        "is_default": "True",
        "name": "Imprecise Subject Location",
        "organization_fides_key": "default_organization",
        "parent_key": "user.location",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Imprecise location derived from sensors (more than 500M)."
    },
    {
        "fides_key": "user.location.precise",
        "is_default": "True",
        "name": "Precise Subject Location",
        "organization_fides_key": "default_organization",
        "parent_key": "user.location",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Precise location derived from sensors (less than 500M)."
    },
    {
        "fides_key": "user.name.first",
        "is_default": "True",
        "name": "First Name",
        "organization_fides_key": "default_organization",
        "parent_key": "user.name",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Subject's first name."
    },
    {
        "fides_key": "user.name.last",
        "is_default": "True",
        "name": "Last Name",
        "organization_fides_key": "default_organization",
        "parent_key": "user.name",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "Subject's last, or family, name."
    },
    {
        "fides_key": "user.unique_id.pseudonymous",
        "is_default": "True",
        "name": "Pseudonymous User ID",
        "organization_fides_key": "default_organization",
        "parent_key": "user.unique_id",
        "replaced_by": "",
        "tags": "",
        "version_added": "2.0.0",
        "version_deprecated": "",
        "description": "A pseudonymous, or probabilistic identifier generated from other subject or device data belonging to the subject."
    },
    {
        "fides_key": "user.personality_rights.tracking",
        "is_default": "True",
        "name": "User Behavior Tracking",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights",
        "replaced_by": "",
        "tags": "tracking_data",
        "version_added": "user_behavior_data",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.tracking.content",
        "is_default": "True",
        "name": "Content Interaction",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.tracking",
        "replaced_by": "",
        "tags": "viewed_content",
        "version_added": "interacted_content",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.tracking.social",
        "is_default": "True",
        "name": "Social Media Engagement",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.tracking",
        "replaced_by": "",
        "tags": "social_media_posts",
        "version_added": "engagement_metrics",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.tracking.browsing",
        "is_default": "True",
        "name": "Web Browsing Behavior",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.tracking",
        "replaced_by": "",
        "tags": "visited_websites",
        "version_added": "browsing_history",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.security",
        "is_default": "True",
        "name": "Security Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights",
        "replaced_by": "",
        "tags": "security_settings",
        "version_added": "privacy_preferences",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.security.privacy",
        "is_default": "True",
        "name": "Privacy Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.security",
        "replaced_by": "",
        "tags": "data_sharing_settings",
        "version_added": "consent_options",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.security.authentication",
        "is_default": "True",
        "name": "Authentication Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.security",
        "replaced_by": "",
        "tags": "login_methods",
        "version_added": "authentication_settings",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.security.device",
        "is_default": "True",
        "name": "Device Security Settings",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.security",
        "replaced_by": "",
        "tags": "device_lock_options",
        "version_added": "biometric_settings",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.expression",
        "is_default": "True",
        "name": "Expressive Output",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights",
        "replaced_by": "",
        "tags": "voice",
        "version_added": "text",
        "version_deprecated": "image",
        "description": "behavior"
    },
    {
        "fides_key": "user.personality_rights.expression.communication",
        "is_default": "True",
        "name": "Communication Style",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.expression",
        "replaced_by": "",
        "tags": "tone",
        "version_added": "vocabulary",
        "version_deprecated": "sentence structure",
        "description": "2.0.0"
    },
    {
        "fides_key": "user.personality_rights.expression.creative_output",
        "is_default": "True",
        "name": "Creative Output",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.expression",
        "replaced_by": "",
        "tags": "generated_content",
        "version_added": "artistic_style",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.perception",
        "is_default": "True",
        "name": "Public Perception",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights",
        "replaced_by": "",
        "tags": "sentiment_analysis",
        "version_added": "inferred_traits",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.perception.inferred_traits",
        "is_default": "True",
        "name": "Inferred Traits",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.perception",
        "replaced_by": "",
        "tags": "personality_type",
        "version_added": "interests",
        "version_deprecated": "values",
        "description": "2.0.0"
    },
    {
        "fides_key": "user.personality_rights.perception.sentiment_analysis",
        "is_default": "True",
        "name": "Sentiment Analysis",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.perception",
        "replaced_by": "",
        "tags": "sentiment_towards_topics",
        "version_added": "emotional_tone",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.preferences",
        "is_default": "True",
        "name": "User Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights",
        "replaced_by": "",
        "tags": "content_preferences",
        "version_added": "interaction_style",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.preferences.content_preferences",
        "is_default": "True",
        "name": "Content Preferences",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.preferences",
        "replaced_by": "",
        "tags": "preferred_topics",
        "version_added": "humor style",
        "version_deprecated": "2.0.0",
        "description": ""
    },
    {
        "fides_key": "user.personality_rights.preferences.interaction_style",
        "is_default": "True",
        "name": "Interaction Style",
        "organization_fides_key": "default_organization",
        "parent_key": "user.personality_rights.preferences",
        "replaced_by": "",
        "tags": "level_of_formality",
        "version_added": "preferred_communication_channels",
        "version_deprecated": "2.0.0",
        "description": ""
    }
];
// Define the convertToTree function
export function convertToTree(data) {
    var tree = {};
    var nodeMap = {};
    // Iterate through the input data
    data.forEach(function (item) {
        var node = {
            name: item.name,
            children: []
        };
        // If the 'size' property exists, add it to the node
        if (item.size !== undefined) {
            node.size = item.size;
        }
        // Store reference to the node in the nodeMap
        nodeMap[item.fides_key] = node;
        // If this node has a parent, add it as a child to the parent
        if (item.parent_key && nodeMap[item.parent_key]) {
            nodeMap[item.parent_key].children.push(node);
        }
        else {
            // Otherwise, it's a root node
            tree[item.fides_key] = node;
        }
    });
    // Return the root nodes as an array
    return Object.values(tree);
}