"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResourceType = void 0;
var ResourceType;
(function (ResourceType) {
    ResourceType["UserAction"] = "UserAction";
    ResourceType["Recommendation"] = "Recommendation";
    ResourceType["Statistic"] = "Statistic";
    ResourceType["Alert"] = "Alert";
    ResourceType["Goal"] = "Goal";
    ResourceType["Persona"] = "Persona";
    ResourceType["StrategicIssue"] = "StrategicIssue";
    ResourceType["BusinessModelCard"] = "BusinessModelCard";
    ResourceType["BrandModelCard"] = "BrandModelCard";
    ResourceType["AIModel"] = "AIModel";
    ResourceType["ModelSubject"] = "ModelSubject";
    ResourceType["ModelTraining"] = "ModelTraining";
    ResourceType["UseCase"] = "UseCase";
    ResourceType["DataConnector"] = "DataConnector";
    ResourceType["Topic"] = "Topic";
    ResourceType["InfoAsset"] = "InfoAsset";
    ResourceType["Policy"] = "Policy";
    ResourceType["DataCategory"] = "DataCategory";
    ResourceType["Message"] = "Message";
    ResourceType["Offer"] = "Offer";
    ResourceType["ScheduledEvent"] = "ScheduledEvent";
    ResourceType["Transaction"] = "Transaction";
    ResourceType["Contract"] = "Contract";
    ResourceType["Workflow"] = "Workflow";
    ResourceType["Task"] = "Task";
    ResourceType["Agent"] = "Agent";
    ResourceType["ProfileAthlete"] = "ProfileAthlete";
    ResourceType["ProfileContract"] = "ProfileContract";
    ResourceType["ProfileModel"] = "ProfileModel";
    ResourceType["ProfileBrand"] = "ProfileBrand";
    ResourceType["ProfileUser"] = "ProfileUser";
    ResourceType["SearchableAthlete"] = "SearchableAthlete";
    ResourceType["SearchableContract"] = "SearchableContract";
    ResourceType["SearchableModel"] = "SearchableModel";
    ResourceType["SearchableBrand"] = "SearchableBrand";
    ResourceType["SearchableUser"] = "SearchableUser";
    ResourceType["Triple"] = "Triple";
    ResourceType["ModelInference"] = "ModelInference";
    ResourceType["scalarString"] = "scalarString";
    ResourceType["ScalarString"] = "ScalarString";
    ResourceType["ScalarInt"] = "ScalarInt";
    ResourceType["ScalarFloat"] = "ScalarFloat";
    ResourceType["ScalarBoolean"] = "ScalarBoolean";
    ResourceType["ScalarDate"] = "ScalarDate";
    ResourceType["ProfileOrganization"] = "ProfileOrganization";
    ResourceType["Interest"] = "Interest";
    ResourceType["Industry"] = "Industry";
})(ResourceType || (exports.ResourceType = ResourceType = {}));
