// config/subscriptionTiers.ts
import { SubscriptionTier, ActionFeatureKey, features } from '@/config/featuresConfig';

export interface SubscriptionTierConfig {
  credits: number;
  monthlyCreditLimit: number;
  featuresUsage: Record<ActionFeatureKey, number>;
}

/**
 * Function to generate initial features usage
 */
const generateFeaturesUsage = () => {
  const usage: Record<ActionFeatureKey, number> = {
    [ActionFeatureKey.CreateRecommendation]: 0,
    [ActionFeatureKey.ReadRecommendation]: 0,
    [ActionFeatureKey.EditRecommendation]: 0,
    [ActionFeatureKey.DeleteRecommendation]: 0,
    [ActionFeatureKey.CreateUserAction]: 0,
    [ActionFeatureKey.ReadUserAction]: 0,
    [ActionFeatureKey.EditUserAction]: 0,
    [ActionFeatureKey.DeleteUserAction]: 0,
    [ActionFeatureKey.CreateGoal]: 0,
    [ActionFeatureKey.ReadGoal]: 0,
    [ActionFeatureKey.EditGoal]: 0,
    [ActionFeatureKey.DeleteGoal]: 0,
    [ActionFeatureKey.CreateUseCase]: 0,
    [ActionFeatureKey.ReadUseCase]: 0,
    [ActionFeatureKey.EditUseCase]: 0,
    [ActionFeatureKey.DeleteUseCase]: 0,
    [ActionFeatureKey.CreateIssue]: 0,
    [ActionFeatureKey.ReadIssue]: 0,
    [ActionFeatureKey.EditIssue]: 0,
    [ActionFeatureKey.DeleteIssue]: 0,
    [ActionFeatureKey.CreateBusinessModel]: 0,
    [ActionFeatureKey.ReadBusinessModel]: 0,
    [ActionFeatureKey.EditBusinessModel]: 0,
    [ActionFeatureKey.DeleteBusinessModel]: 0,
    [ActionFeatureKey.CreateBranding]: 0,
    [ActionFeatureKey.ReadBranding]: 0,
    [ActionFeatureKey.EditBranding]: 0,
    [ActionFeatureKey.DeleteBranding]: 0,
    [ActionFeatureKey.CreateModel]: 0,
    [ActionFeatureKey.ReadModel]: 0,
    [ActionFeatureKey.EditModel]: 0,
    [ActionFeatureKey.DeleteModel]: 0,
    [ActionFeatureKey.CreateTrainModel]: 0,
    [ActionFeatureKey.ReadTrainModel]: 0,
    [ActionFeatureKey.EditTrainModel]: 0,
    [ActionFeatureKey.DeleteTrainModel]: 0,
    [ActionFeatureKey.CreateConnector]: 0,
    [ActionFeatureKey.ReadConnector]: 0,
    [ActionFeatureKey.EditConnector]: 0,
    [ActionFeatureKey.DeleteConnector]: 0,
    [ActionFeatureKey.CreateTopic]: 0,
    [ActionFeatureKey.ReadTopic]: 0,
    [ActionFeatureKey.EditTopic]: 0,
    [ActionFeatureKey.DeleteTopic]: 0,
    [ActionFeatureKey.CreateInfoAsset]: 0,
    [ActionFeatureKey.ReadInfoAsset]: 0,
    [ActionFeatureKey.EditInfoAsset]: 0,
    [ActionFeatureKey.DeleteInfoAsset]: 0,
    [ActionFeatureKey.CreatePolicy]: 0,
    [ActionFeatureKey.ReadPolicy]: 0,
    [ActionFeatureKey.EditPolicy]: 0,
    [ActionFeatureKey.DeletePolicy]: 0,
    [ActionFeatureKey.CreateTerm]: 0,
    [ActionFeatureKey.ReadTerm]: 0,
    [ActionFeatureKey.EditTerm]: 0,
    [ActionFeatureKey.DeleteTerm]: 0,
    [ActionFeatureKey.CreateMessage]: 0,
    [ActionFeatureKey.ReadMessage]: 0,
    [ActionFeatureKey.EditMessage]: 0,
    [ActionFeatureKey.DeleteMessage]: 0,
    [ActionFeatureKey.CreateOffer]: 0,
    [ActionFeatureKey.ReadOffer]: 0,
    [ActionFeatureKey.EditOffer]: 0,
    [ActionFeatureKey.DeleteOffer]: 0,
    [ActionFeatureKey.CreateContract]: 0,
    [ActionFeatureKey.ReadContract]: 0,
    [ActionFeatureKey.EditContract]: 0,
    [ActionFeatureKey.DeleteContract]: 0,
    [ActionFeatureKey.CreateTransaction]: 0,
    [ActionFeatureKey.ReadTransaction]: 0,
    [ActionFeatureKey.EditTransaction]: 0,
    [ActionFeatureKey.DeleteTransaction]: 0,
    [ActionFeatureKey.CreateWorkflow]: 0,
    [ActionFeatureKey.ReadWorkflow]: 0,
    [ActionFeatureKey.EditWorkflow]: 0,
    [ActionFeatureKey.DeleteWorkflow]: 0,
    [ActionFeatureKey.CreateTask]: 0,
    [ActionFeatureKey.ReadTask]: 0,
    [ActionFeatureKey.EditTask]: 0,
    [ActionFeatureKey.DeleteTask]: 0,
    [ActionFeatureKey.CreateScheduledEvent]: 0,
    [ActionFeatureKey.ReadScheduledEvent]: 0,
    [ActionFeatureKey.EditScheduledEvent]: 0,
    [ActionFeatureKey.DeleteScheduledEvent]: 0,
    [ActionFeatureKey.CreateProfileAthlete]: 0,
    [ActionFeatureKey.ReadProfileAthlete]: 0,
    [ActionFeatureKey.EditProfileAthlete]: 0,
    [ActionFeatureKey.DeleteProfileAthlete]: 0,
    [ActionFeatureKey.CreateProfileContract]: 0,
    [ActionFeatureKey.ReadProfileContract]: 0,
    [ActionFeatureKey.EditProfileContract]: 0,
    [ActionFeatureKey.DeleteProfileContract]: 0,
    [ActionFeatureKey.CreateProfileModel]: 0,
    [ActionFeatureKey.ReadProfileModel]: 0,
    [ActionFeatureKey.EditProfileModel]: 0,
    [ActionFeatureKey.DeleteProfileModel]: 0,
    [ActionFeatureKey.CreateProfileBrand]: 0,
    [ActionFeatureKey.ReadProfileBrand]: 0,
    [ActionFeatureKey.EditProfileBrand]: 0,
    [ActionFeatureKey.DeleteProfileBrand]: 0,
    [ActionFeatureKey.CreateProfileUser]: 0,
    [ActionFeatureKey.ReadProfileUser]: 0,
    [ActionFeatureKey.EditProfileUser]: 0,
    [ActionFeatureKey.DeleteProfileUser]: 0,
    [ActionFeatureKey.CreateSearchableAthlete]: 0,
    [ActionFeatureKey.ReadSearchableAthlete]: 0,
    [ActionFeatureKey.EditSearchableAthlete]: 0,
    [ActionFeatureKey.DeleteSearchableAthlete]: 0,
    [ActionFeatureKey.CreateSearchableContract]: 0,
    [ActionFeatureKey.ReadSearchableContract]: 0,
    [ActionFeatureKey.EditSearchableContract]: 0,
    [ActionFeatureKey.DeleteSearchableContract]: 0,
    [ActionFeatureKey.CreateSearchableModel]: 0,
    [ActionFeatureKey.ReadSearchableModel]: 0,
    [ActionFeatureKey.EditSearchableModel]: 0,
    [ActionFeatureKey.DeleteSearchableModel]: 0,
    [ActionFeatureKey.CreateSearchableBrand]: 0,
    [ActionFeatureKey.ReadSearchableBrand]: 0,
    [ActionFeatureKey.EditSearchableBrand]: 0,
    [ActionFeatureKey.DeleteSearchableBrand]: 0,
    [ActionFeatureKey.CreateSearchableUser]: 0,
    [ActionFeatureKey.ReadSearchableUser]: 0,
    [ActionFeatureKey.EditSearchableUser]: 0,
    [ActionFeatureKey.DeleteSearchableUser]: 0,
    [ActionFeatureKey.ReadAnalytics]: 0,
    [ActionFeatureKey.ExportAnalytics]: 0,
    [ActionFeatureKey.CreateBrandingCard]: 0,
    [ActionFeatureKey.ReadBrandingCard]: 0,
    [ActionFeatureKey.EditBrandingCard]: 0,
    [ActionFeatureKey.DeleteBrandingCard]: 0,
    [ActionFeatureKey.FacetsPerBrandingCardType]: 0,
    [ActionFeatureKey.CreateStatistic]: 0,
    [ActionFeatureKey.ReadStatistic]: 0,
    [ActionFeatureKey.EditStatistic]: 0,
    [ActionFeatureKey.DeleteStatistic]: 0,
    [ActionFeatureKey.CreateAlert]: 0,
    [ActionFeatureKey.ReadAlert]: 0,
    [ActionFeatureKey.EditAlert]: 0,
    [ActionFeatureKey.DeleteAlert]: 0,
    [ActionFeatureKey.CreatePersona]: 0,
    [ActionFeatureKey.ReadPersona]: 0,
    [ActionFeatureKey.EditPersona]: 0,
    [ActionFeatureKey.DeletePersona]: 0,
    [ActionFeatureKey.CreateAgent]: 0,
    [ActionFeatureKey.ReadAgent]: 0,
    [ActionFeatureKey.EditAgent]: 0,
    [ActionFeatureKey.DeleteAgent]: 0,
    [ActionFeatureKey.CreateModelSubject]: 0,
    [ActionFeatureKey.ReadModelSubject]: 0,
    [ActionFeatureKey.EditModelSubject]: 0,
    [ActionFeatureKey.DeleteModelSubject]: 0,
    [ActionFeatureKey.CreateModelTraining]: 0,
    [ActionFeatureKey.ReadModelTraining]: 0,
    [ActionFeatureKey.EditModelTraining]: 0,
    [ActionFeatureKey.DeleteModelTraining]: 0,
    [ActionFeatureKey.ReadProfileView]: 0,
    [ActionFeatureKey.EditProfile]: 0,
    [ActionFeatureKey.ConnectWallet]: 0,
    [ActionFeatureKey.ManageAccount]: 0
  };

  // Iterate over all features and their actions
  for (const feature of features) {
    for (const action of feature.actions) {
      usage[action.actionKey] = 0;
    }
  }

  return usage;
};

/**
 * Generate Subscription Tiers Configuration
 */
const generateSubscriptionTiers = () => {
  const usage = generateFeaturesUsage();
  const tiersConfig: Record<SubscriptionTier, SubscriptionTierConfig> = {
    [SubscriptionTier.FREE]: {
      credits: 0,
      monthlyCreditLimit: 100,
      featuresUsage: { ...usage },
    },
    [SubscriptionTier.PRO]: {
      credits: 0,
      monthlyCreditLimit: 500,
      featuresUsage: { ...usage },
    },
    [SubscriptionTier.ENTERPRISE]: {
      credits: 0,
      monthlyCreditLimit: 1000,
      featuresUsage: { ...usage },
    },
  };
  return tiersConfig;
};

export const subscriptionTiers = generateSubscriptionTiers();
